# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
out = "out"
script = "script"
solc = "0.8.25"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
sepolia = "https://rpc2.sepolia.org"
gnosis = "https://rpc.ankr.com/gnosis"
arbitrum = "https://rpc.ankr.com/arbitrum"
base = "https://rpc.ankr.com/base"
localhost = "http://localhost:8545"
